[build]
  command   = "npm run build"
  publish   = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,NEXT_PUBLIC_SUPABASE_URL,RESEND_FROM_EMAIL,RESEND_TO_EMAIL,SUPABASE_SERVICE_ROLE_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"
