/**
 * cisco.ts — Export ParsedCallFlow as Cisco UCCX/UCCE-compatible XML
 * Produces a simplified Cisco Script Application XML skeleton.
 */
import type { ParsedCallFlow } from '@/lib/parser';

function escapeXml(s: string): string {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

export function toCiscoXml(flow: ParsedCallFlow, scriptName = 'MainIVR'): string {
  const date = new Date().toISOString().split('T')[0];

  const menuSteps = flow.options.map(opt => `
    <Step type="Menu" key="${opt.key}">
      <Label>${escapeXml(opt.label)}</Label>
      <Action type="TransferToQueue">
        <Queue>${escapeXml(opt.queue)}</Queue>
      </Action>
    </Step>`).join('');

  const afterHours = flow.after_hours ? `
  <AfterHoursRouting>
    <Destination>${escapeXml(flow.after_hours)}</Destination>
  </AfterHoursRouting>` : '';

  const holiday = flow.holiday ? `
  <HolidayRouting>
    <Message>${escapeXml(flow.holiday)}</Message>
  </HolidayRouting>` : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by AI4 Contact Center Script Builder — ${date} -->
<CiscoScript name="${escapeXml(scriptName)}" version="1.0">

  <Metadata>
    <CreatedAt>${date}</CreatedAt>
    <Generator>AI4 Contact Center · Apropos Group LLC</Generator>
  </Metadata>

  <CallFlow>
    <Entry type="IncomingCall"/>

    <Menu name="${escapeXml(flow.menu)}" type="DTMF" timeout="5" maxRetries="2">
      ${menuSteps.trim()}
    </Menu>
    ${afterHours}
    ${holiday}
  </CallFlow>

</CiscoScript>`;
}
