/**
 * genesys.ts — Export ParsedCallFlow as Genesys Cloud Architect-compatible JSON
 * Produces a simplified Architect inbound call flow skeleton.
 */
import type { ParsedCallFlow } from '@/lib/parser';

export function toGenesysArchitect(flow: ParsedCallFlow): object {
  const date = new Date().toISOString();

  const menuActions = flow.options.map(opt => ({
    id: `action_${opt.key}`,
    type: 'transferToAcd',
    name: `Transfer to ${opt.label}`,
    queue: { name: opt.queue },
    dtmfKey: `${opt.key}`,
  }));

  return {
    $schema: 'https://developer.genesys.cloud/routing/architect/schema/inbound-call-flow/v1',
    name: flow.menu,
    description: `Generated by AI4 Contact Center Script Builder — ${date.split('T')[0]}`,
    type: 'InboundCall',
    division: 'Home',
    createdDate: date,
    modifiedDate: date,
    startUpRef: '/inboundcallflows/tasks/subflows/main.subflow',
    defaultLanguage: 'en-us',
    variables: [],
    mainMenu: {
      id: 'main_menu',
      name: flow.menu,
      type: 'CollectDigits',
      prompt: {
        type: 'tts',
        text: `Thank you for calling. ${flow.options.map(o => `Press ${o.key} for ${o.label}.`).join(' ')}`,
      },
      timeout: 5,
      noInputCount: 2,
      noMatchCount: 2,
      actions: menuActions,
    },
    afterHours: flow.after_hours
      ? { type: 'transferToVoicemail', target: flow.after_hours }
      : null,
    holiday: flow.holiday
      ? { type: 'playAnnouncement', announcement: flow.holiday }
      : null,
  };
}
