/**
 * twilio.ts — Export ParsedCallFlow as Twilio Studio Flow JSON
 * Produces a Twilio Studio-compatible flow definition with gather widgets.
 */
import type { ParsedCallFlow } from '@/lib/parser';

export function toTwilioStudio(flow: ParsedCallFlow): object {
  const states: object[] = [];
  const transitions: object[] = [];

  // Trigger state
  states.push({
    name: 'Trigger',
    type: 'trigger',
    transitions: [{ event: 'incomingCall', next: 'MainMenu' }],
    properties: {},
  });

  // Main menu gather
  const gatherTransitions = flow.options.map(opt => ({
    event: 'keypress',
    conditions: [{ friendly_name: `Pressed ${opt.key}`, type: 'equal_to', value: `${opt.key}`, variable: 'widgets.MainMenu.Digits' }],
    next: `Queue_${opt.queue}`,
  }));

  if (flow.after_hours) {
    gatherTransitions.push({ event: 'timeout', conditions: [], next: 'AfterHours' });
  }
  gatherTransitions.push({ event: 'no_input', conditions: [], next: 'RepeatMenu' });

  states.push({
    name: 'MainMenu',
    type: 'gather-input-on-call',
    transitions: gatherTransitions,
    properties: {
      say: `Thank you for calling. ${flow.options.map(o => `Press ${o.key} for ${o.label}.`).join(' ')}`,
      language: 'en-US',
      voice: 'Polly.Joanna',
      timeout: 5,
    },
  });

  // Queue states
  flow.options.forEach(opt => {
    states.push({
      name: `Queue_${opt.queue}`,
      type: 'enqueue-call',
      transitions: [{ event: 'callComplete', next: 'Hangup' }],
      properties: {
        queue_name: opt.queue,
        friendly_name: opt.label,
      },
    });
  });

  // Repeat
  states.push({
    name: 'RepeatMenu',
    type: 'redirect',
    transitions: [{ event: 'next', next: 'MainMenu' }],
    properties: { url: '' },
  });

  // After hours
  if (flow.after_hours) {
    states.push({
      name: 'AfterHours',
      type: 'send-to-flex',
      transitions: [{ event: 'callComplete', next: 'Hangup' }],
      properties: { channel: flow.after_hours, workflow_sid: 'ENTER_WORKFLOW_SID' },
    });
  }

  // Holiday
  if (flow.holiday) {
    states.push({
      name: 'Holiday',
      type: 'say-play',
      transitions: [{ event: 'audioComplete', next: 'Hangup' }],
      properties: {
        say: `We are currently closed for the holiday. ${flow.holiday.replace(/_/g, ' ')}. Please call back during normal business hours.`,
        voice: 'Polly.Joanna',
        language: 'en-US',
      },
    });
  }

  // Hangup
  states.push({
    name: 'Hangup',
    type: 'hangup',
    transitions: [],
    properties: {},
  });

  return {
    description: `${flow.menu} — Generated by AI4 Contact Center`,
    states,
    initial_state: 'Trigger',
    flags: { allow_concurrent_calls: true },
  };
}
