'use client';
import { useEffect, useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import TranscriptIntelligenceDashboard from '@/components/TranscriptIntelligenceDashboard';
import type { FlowMappingResult, IntelligenceReport, NormalizedTranscript, TranscriptAnalysis } from '@/lib/transcriptIntelligenceEngine';

type LiveInteraction = { id:string; channel:string; customer_identifier:string|null; status:string; started_at:string; queue?:{name:string}|null; agent?:{name:string}|null; route?:{intent:string|null}|null };
const EXAMPLE_TRANSCRIPT = `[09:00:12] Customer: Hi, I keep getting sent back to the same billing menu and my payment still fails.\n[09:00:31] Agent: I am sorry you are experiencing this. Let me check the account and routing.\n[09:01:05] Customer: This is the third time I called and it is very frustrating.\n[09:01:42] Agent: I can transfer you to a billing specialist and escalate if needed.\n[09:02:10] Customer: Please escalate to a supervisor if this is not fixed today.`;

export default function TranscriptIntelligencePage() {
  const [inputText,setInputText]=useState(EXAMPLE_TRANSCRIPT); const [fileMeta,setFileMeta]=useState<{fileName?:string;mimeType?:string}>({});
  const [report,setReport]=useState<IntelligenceReport|null>(null); const [isRunning,setIsRunning]=useState(false); const [error,setError]=useState<string|null>(null);
  const [interactions,setInteractions]=useState<LiveInteraction[]>([]); const [selectedId,setSelectedId]=useState(''); const [liveSource,setLiveSource]=useState<LiveInteraction|null>(null);

  async function loadInteractions(){ try{const r=await fetch('/api/runtime/interactions');const d=await r.json();if(!r.ok)throw new Error(d?.error??'Failed to load live interactions');const list=(d.interactions??[]) as LiveInteraction[];setInteractions(list);if(!selectedId&&list[0])setSelectedId(list[0].id);}catch(e){setError((e as Error).message);} }
  useEffect(()=>{void loadInteractions();},[]);
  async function handleFileUpload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{setInputText(await f.text());setFileMeta({fileName:f.name,mimeType:f.type});setError(null);setLiveSource(null);}catch{setError('Failed to read transcript file.');}}
  async function handleAnalyze(){setError(null);setIsRunning(true);setReport(null);setLiveSource(null);try{const ir=await fetch('/api/transcripts/ingest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:inputText,...fileMeta})});const id=await ir.json();if(!ir.ok)throw new Error(id?.error??'Failed to ingest transcript');const transcript=id as NormalizedTranscript;const ar=await fetch('/api/transcripts/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript})});const ad=await ar.json();if(!ar.ok)throw new Error(ad?.error??'Failed to analyze transcript');const mr=await fetch('/api/transcripts/map-flow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript})});const md=await mr.json();if(!mr.ok)throw new Error(md?.error??'Failed to map transcript');const rr=await fetch('/api/transcripts/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript,analysis:ad as TranscriptAnalysis,flowMapping:md as FlowMappingResult})});const rd=await rr.json();if(!rr.ok)throw new Error(rd?.error??'Failed to generate report');setReport(rd);}catch(e){setError((e as Error).message);}finally{setIsRunning(false);}}
  async function analyzeLive(){if(!selectedId)return;setError(null);setIsRunning(true);setReport(null);try{const r=await fetch(`/api/transcripts/live?interactionId=${encodeURIComponent(selectedId)}`);const d=await r.json();if(!r.ok)throw new Error(d?.error??'Failed to analyze live interaction');setReport(d.report as IntelligenceReport);setLiveSource(d.interaction as LiveInteraction);setInputText((d.report as IntelligenceReport).transcript.rawText);setFileMeta({fileName:`live-${selectedId}.txt`,mimeType:'text/plain'});}catch(e){setError((e as Error).message);}finally{setIsRunning(false);}}
  function handleDownloadReport(){if(!report)return;const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='intelligence-report.json';a.click();URL.revokeObjectURL(url);}
  return <><Header/><main style={{minHeight:'100vh',background:'#06111f',color:'#e8f0fe',fontFamily:"'Inter','Jost',sans-serif",padding:'2rem clamp(1rem,4vw,3rem)'}}><div style={{maxWidth:'1180px',margin:'0 auto'}}>
    <p style={{fontSize:'.66rem',fontWeight:700,letterSpacing:'.2em',textTransform:'uppercase',color:'#5bd3ff',marginBottom:'.4rem'}}>AI4 Contact Center · Transcript Intelligence</p>
    <h1 style={{margin:'0 0 1rem',color:'#fff',fontSize:'clamp(1.6rem,3vw,2.3rem)'}}>Conversation Transcript Ingestion & Intelligence Engine</h1>
    <section style={{background:'rgba(91,211,255,.05)',border:'1px solid rgba(91,211,255,.28)',borderRadius:8,padding:'.9rem',marginBottom:'.9rem'}}>
      <h3 style={{margin:'0 0 .55rem',fontSize:'.85rem',textTransform:'uppercase',letterSpacing:'.08em'}}>Live Canonical Runtime</h3>
      <p style={{margin:'0 0 .65rem',fontSize:'.78rem',color:'rgba(255,255,255,.68)'}}>Analyze a completed Voice, SMS, or Web Chat interaction directly from the canonical AI4CC transcript store. No upload or copy/paste required.</p>
      <div style={{display:'flex',gap:'.6rem',flexWrap:'wrap'}}><select value={selectedId} onChange={e=>setSelectedId(e.target.value)} style={{flex:'1 1 320px',minWidth:0,background:'#0a1a2a',color:'#fff',border:'1px solid rgba(255,255,255,.16)',borderRadius:7,padding:'.7rem'}}>{interactions.map(i=><option key={i.id} value={i.id}>{i.channel.toUpperCase()} · {i.route?.intent??'unclassified'} · {i.queue?.name??'No queue'} · {i.status} · {i.id.slice(0,8)}</option>)}</select><button onClick={analyzeLive} disabled={!selectedId||isRunning} style={{background:'#5bd3ff',color:'#06111f',border:0,borderRadius:7,padding:'.7rem 1rem',fontWeight:800}}>Analyze Live Interaction</button><button onClick={()=>void loadInteractions()} style={{background:'rgba(255,255,255,.06)',color:'#fff',border:'1px solid rgba(255,255,255,.16)',borderRadius:7,padding:'.7rem 1rem'}}>Refresh</button></div>
      {liveSource&&<p style={{margin:'.65rem 0 0',fontSize:'.74rem',color:'#8fdfff'}}>Canonical source: {liveSource.channel.toUpperCase()} · {liveSource.queue?.name??'No queue'} · {liveSource.agent?.name??'Unassigned'} · {liveSource.status}</p>}
    </section>
    <TranscriptIntelligenceDashboard inputText={inputText} onInputTextChange={v=>{setInputText(v);setLiveSource(null)}} onFileUpload={handleFileUpload} onAnalyze={handleAnalyze} onDownloadReport={handleDownloadReport} report={report} isRunning={isRunning} error={error}/>
  </div></main><Footer/></>;
}
